### ISSUE TITLE
Roadmap for Subset 1 Implementation

### ISSUE THREAD

**Issue by hrszpuk** [dragonfly-lang/dragonfly#2]
The project's development has been split up into subset implementations. Instead of implementing everything at once, a specific subset of the language will be implemented. This is then repeated until the compilers works with the entire language. The advantage of this is fast, lighter implementation phases which will work well with university (sometime I have a lot of free time, other time I have very little). 

This subset implementation takes course over January. Unfortunately, January is an exam period for me and therefore this implementation is light, with only basic programming concepts being implemented.

## Subset 1 implementation features
This implementation phase focuses on common programming concepts such as variables, constants, while loops, if-else statements, and basic input/output (println and input). Only the types `int` and `string` will be implemented, with no methods or traits provided for them.

```
/* This is everything that is in this implementation phase. */
let x int = (1 + 5 + 4) / 10 * 5 
const msg string = "Hello, World"

if (x*3) == 20 {
    println(msg)
} else if 3 + 7 / 10 > x {
    println("hahaha")
} else {
    println("Nah")
} 

let user_input = input("Input ")
while x > 0 {
    for c in user_input {
        x -= 1
    }
}
println("That's it I guess!")
```

## Tasks
- [ ] Main 
  - [x] Set up CLI arguments:
    - [x] `dragon <file.drg>`  
  - [x] Set up CLI flags:
    - [x] `-h`,`--help` - Display helpful information
    - [ ] `-l`,`--lex` - stop after lexing and print tokens
    - [ ] `-p`,`--parse` - stop after parsing and print AST
    - [ ] `-c`,`--check` - stop after type checking and print AST
    - [ ] `-g`,`--gen` - stop after code generation and print LLVM IR
    - [x] `-o`,`--output` - Change output name
  - [ ] Hook up functions/classes to complete the commands/flags given 
- [x] Scanning
  - [x] #4
  - [x] #5
  - [x] #6
- [ ] Parsing
  - [x] #7
    - [x] Variable/Constant Declaration Node
    - [x] Variable/Constant Assignment Node
    - [x] While Loop Node
    - [x] For Loop Node
    - [x] If-Else Node
    - [x] Function Call Node
  - [x] #8
  - [ ] #9
- [ ] Semantics
  - [ ] #10
    - [ ] Duplicate variable/constant identifier
    - [ ] Duplicate function call identifier
    - [ ] Non-boolean expression for while loop
    - [ ] Non-boolean expression for if statement
    - [ ] For loop expression isn't iterable
    - [ ] Function call argument type doesn't match parameter type
  - [ ] #11
  - [ ] #12
- [ ] LLVM code generation
  - [ ] Read LLVM Kaleidoscope
  - [ ] Plan code generation
- [ ] LLVM code execution
  - [ ] Read LLVM Kaleidoscope
  - [ ] Plan code execution 

I expect more issues will be created from this list for feature tracking.
